### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-es-operator#15]
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 33:
│   33: variable "cluster_type" {
│ 
│ The root module input variable "cluster_type" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
Error: Process completed with exit code 1.

**Comment by balasgit** [comment]
Fixed all issues and PR is complete. After PR Merge, it fails on main

More details - https://github.com/cloud-native-toolkit/terraform-gitops-cp-es-operator/actions/runs/3138061766

Error: External Program Execution Failed
│ 
│   with module.dev_cluster.data.external.oc_login,
│   on .terraform/modules/dev_cluster/main.tf line 32, in data "external" "oc_login":
│   32:   program = ["bash", "${path.module}/scripts/oc-login.sh"]
│ 
│ The data source received an unexpected error while attempting to execute
│ the program.
│ 
│ Program: /bin/bash
│ Error Message: error: dial tcp 169.63.160.130:30768: connect: connection
│ refused - verify you have provided the correct host and port and that the
│ server is currently running.
│ Error logging in to https://c104-e.us-east.containers.cloud.ibm.com:30768/
│ with kubeconfig=/tmp/workspace/.tmp/.kube/config, auth=username(apikey),
│ and cert_file=
│ cat: can't open '': No such file or directory
│ cert size: 0
│ I0927 21:27:22.824281    1822 loader.go:372] Config loaded from file:
│ /tmp/workspace/.tmp/.kube/config
│ I0927 21:27:22.824416    1822 round_trippers.go:466] curl -v -XHEAD
│ 'https://c104-e.us-east.containers.cloud.ibm.com:30768/'
│ I0927 21:27:22.827356    1822 round_trippers.go:495] HTTP Trace: DNS Lookup
│ for c104-e.us-east.containers.cloud.ibm.com resolved to [{169.63.160.130 }]
│ I0927 21:27:22.899285    1822 round_trippers.go:508] HTTP Trace: Dial to
│ tcp:169.63.160.130:30768 failed: dial tcp 169.63.160.130:30768: connect:
│ connection refused
│ I0927 21:27:22.899397    1822 round_trippers.go:570] HTTP Statistics:
│ DNSLookup 2 ms Dial 71 ms TLSHandshake 0 ms Duration 74 ms
│ I0927 21:27:22.899404    1822 round_trippers.go:577] Response Headers:
│ F0927 21:27:22.899447    1822 helpers.go:118] error: dial tcp
│ 169.63.160.130:30768: connect: connection refused - verify you have
│ provided the correct host and port and that the server is currently
│ running.
│ goroutine 1 [running]:
│ k8s.io/klog/v2.stacks(0x1)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1140 +0x8a
│ k8s.io/klog/v2.(*loggingT).output(0x5cd9fa0, 0x3, 0x0, 0xc000039b90, 0x2,
│ {0x49acfb3, 0x10}, 0xc00007a800, 0x0)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1088 +0x66f
│ k8s.io/klog/v2.(*loggingT).printDepth(0xc0009faaa0, 0xa0, 0x0, {0x0, 0x0},
│ 0xc0000c8b00, {0xc0005e4ee0, 0x1, 0x1})
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:735 +0x1ae
│ k8s.io/klog/v2.FatalDepth(...)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1628
│ k8s.io/kubectl/pkg/cmd/util.fatal({0xc0009faaa0, 0xa0}, 0xc0009b35c0)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:96
│ +0xc5
│ k8s.io/kubectl/pkg/cmd/util.checkErr({0x4173740, 0xc0005e4d60}, 0x3e6e690)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:191
│ +0x7d7
│ k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:118
│ github.com/openshift/oc/pkg/cli/login.NewCmdLogin.func1(0xc0009ba280,
│ {0xc0005e17a0, 0x1, 0x6})
│ 	/go/src/github.com/openshift/oc/pkg/cli/login/login.go:77 +0x39f
│ github.com/spf13/cobra.(*Command).execute(0xc0009ba280, {0xc0005e1740, 0x6,
│ 0x6})
│ 	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:860
│ +0x5f8
│ github.com/spf13/cobra.(*Command).ExecuteC(0xc0009ba000)
│ 	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:974
│ +0x3bc
│ github.com/spf13/cobra.(*Command).Execute(...)
│ 	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:902
│ k8s.io/component-base/cli.run(0xc0009ba000)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/component-base/cli/run.go:146
│ +0x325
│ k8s.io/component-base/cli.RunNoErrOutput(...)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/component-base/cli/run.go:84
│ main.main()
│ 	/go/src/github.com/openshift/oc/cmd/oc/oc.go:77 +0x365
│ 
│ goroutine 19 [chan receive]:
│ k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1283 +0x6a
│ created by k8s.io/klog/v2.init.0
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:420 +0xfb
│ 
│ goroutine 9 [select]:
│ io.(*pipe).Read(0xc00093b6e0, {0xc000952000, 0x1000, 0x1})
│ 	/opt/rh/go-toolset-1.17/root/usr/lib/go-toolset-1.17-golang/src/io/pipe.go:57
│ +0xb7
│ io.(*PipeReader).Read(0x0, {0xc000952000, 0x0, 0x0})
│ 	/opt/rh/go-toolset-1.17/root/usr/lib/go-toolset-1.17-golang/src/io/pipe.go:134
│ +0x25
│ bufio.(*Scanner).Scan(0xc000134480)
│ 	/opt/rh/go-toolset-1.17/root/usr/lib/go-toolset-1.17-golang/src/bufio/scan.go:215
│ +0x865
│ github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter.func1()
│ 	/go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:527
│ +0x105
│ created by github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter
│ 	/go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:526
│ +0x21a
│ 
│ goroutine 10 [select]:
│ k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x41779e0,
│ 0xc000954000}, 0x1, 0xc000102360)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167
│ +0x13b
│ k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x12a05f200, 0x0, 0x0,
│ 0x0)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
│ +0x89
│ k8s.io/apimachinery/pkg/util/wait.Until(...)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
│ k8s.io/apimachinery/pkg/util/wait.Forever(0x0, 0x0)
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81
│ +0x28
│ created by k8s.io/component-base/logs.InitLogs
│ 	/go/src/github.com/openshift/oc/vendor/k8s.io/component-base/logs/logs.go:179
│ +0x85
│ 
│ State: exit status 1
╵
Error: Process completed with exit code 1.

**Comment by balasgit** [comment]
Fixed issues
